# Anotación

# **Annotating Genomic Data**

## **Annotating genomes**

[Annotation](https://en.wikipedia.org/wiki/DNA_annotation) is the process of identifying the coordinates of genes and all the coding regions in a genome and determining what proteins are produced from them. In order to do this, an unknown sequence is enriched with information relating to genomic position, regulatory sequences, repeats, gene names, and protein products. This information is stored in genomic databases to help future analysis processing of new data.

[Prokka](https://github.com/tseemann/prokka) is a command-line software tool created in Perl to annotate bacterial, archaeal and viral genomes and reproduce standards-compliant output files. It requires preassembled genomic DNA sequences in FASTA format as input file, which is the only mandatory parameter to the software. For annotation, Prokka relies on external features and databases to identify the genomic features within the contigs.

| Tool (reference)                    | Features predicted         |
|:------------------------------------|:---------------------------|
| Prodigal (Hyatt 2010)               | Coding Sequences (CDS)     |
| RNAmmer (Lagesen et al., 2007)      | Ribosomal RNA genes (rRNA) |
| Aragorn (Laslett and Canback, 2004) | Transfer RNA genes         |
| SignalP (Petersen et al., 2011)     | Signal leader peptides     |
| Infernal (Kolbe and Eddy, 2011)     | Non-coding RNAs            |

Protein coding genes are annotated in two stages. Prodigal identifies the coordinates of candidate genes, but does not describe the putative gene product. Usually, in order to predict what a gene encodes for, it is compared with a large database of known sequences, usually at the protein level, and transferred the annotation of the best significant match. Prokka uses this method but in a hierarchical manner. It starts with a small trustworthy database, it then moves to medium sized but domain-specific databases and finally curated models of protein families.

In this lesson, we’ll annotate the `FASTA` files we have downloaded in the previous lesson. First, we need to create a new directory where our annotated genomes will be.

``` bash
$ mkdir -p ~/pan_workshop/results/annotated/
$ cd ~/pan_workshop/results/annotated/
$ conda deactivate
$ conda activate /miniconda3/envs/Prokka_Global
```

Once inside the environment, we are ready to run our first annotation.

``` bash
(Prokka_Global) $
```

In this example, we will use the following options:

| Code | Meaning |
|:-----------------------------------|:-----------------------------------|
| –prefix | Filename output prefix \[auto\] (default ‘’) |
| –outdir | Output folder \[auto\] (default ‘’) |
| –kingdom | Annotation mode: Archaea Bacteria Mitochondria Viruses (default ‘Bacteria’) |
| –genus | Genus name (default ‘Genus’) |
| –strain | Strain name (default ‘strain’) |
| –usegenus | Use genus-specific BLAST databases (needs –genus) (default OFF) |
| –addgens | Add ‘gene’ features for each ‘CDS’ feature (default OFF) |

``` bash
$ prokka --prefix agalactiae_515_prokka --outdir agalactiae_515_prokka --kingdom Bacteria --genus Streptococcus --species agalactiae --strain 515 --usegenus --addgenes ~/pan_workshop/data/agalactiae_515/GCF_012593885.1_ASM1259388v1_genomic.fna
```

This command takes about a minute to run, printing a lot of information on the screen while doing so. After finishing, Prokka will create a new folder, inside of which, if you run the `tree` command, you will find the following files:

``` bash
tree
```

::: callout-note
## Output

```         
.
└── agalactiae_515_prokka
    ├── agalactiae_515_prokka.err
    ├── agalactiae_515_prokka.faa
    ├── agalactiae_515_prokka.ffn
    ├── agalactiae_515_prokka.fna
    ├── agalactiae_515_prokka.fsa
    ├── agalactiae_515_prokka.gbk
    ├── agalactiae_515_prokka.gff
    ├── agalactiae_515_prokka.log
    ├── agalactiae_515_prokka.sqn
    ├── agalactiae_515_prokka.tbl
    ├── agalactiae_515_prokka.tsv
    └── agalactiae_515_prokka.txt

1 directory, 12 files
```
:::

We encourage you to explore each output. The following table describes the contents of each output file:

| Extension | Description |
|:-----------------------------------|:-----------------------------------|
| .gff | This is the master annotation in GFF3 format, containing both sequences and annotations. It can be viewed directly in Artemis or IGV. |
| .gbk | This is a standard GenBank file derived from the master `.gff`. If the input to Prokka was a multi-FASTA, then this will be a multi-GenBank, with one record for each sequence. |
| .fna | Nucleotide FASTA file of the input contig sequences. |
| .faa | Protein FASTA file of the translated CDS sequences. |
| .ffn | Nucleotide FASTA file of all the prediction transcripts (CDS, rRNA, tRNA, tmRNA, misc_RNA). |
| .sqn | An ASN1 format “Sequin” file for submission to GenBank. It needs to be edited to set the correct taxonomy, authors, related publications etc. |
| .fsa | Nucleotide FASTA file of the input contig sequences, used by “tbl2asn” to create the `.sqn` file. It is almost the same as the `.fna` file but with extra Sequin tags in the sequence description lines. |
| .tbl | Feature Table file, used by “tbl2asn” to create the `.sqn` file. |
| .err | Unacceptable annotations - the NCBI discrepancy report. |
| .log | Contains all the output that Prokka produced during its run. This is the record of the used settings, even if the `--quiet` option was enabled. |
| .txt | Statistics related to the found annotated features. |
| .tsv | Tab-separated file of all features: locus_tag, ftype, len_bp, gene, EC_number, COG, product. |

Parameters can be modified as much as needed regarding the organism, the gene, and even the locus tag you are looking for.

:::: callout-note
## Exercise 1(Begginer): Inspecting the GBK

Open the `gbk` output file and carefully explore the information it contains. Which of the following statements is TRUE?

a\) Prokka translates every single gene to its corresponding protein, even if the gene isn’t a coding one.\
b) Prokka can find all kinds of protein-coding sequences, not just the ones that have been identified or cataloged in a database.\
c) Prokka identifies tRNA genes but doesn’t mention the anticodon located on the tRNAs.\
d) Prokka doesn’t provide the positions in which a feature starts or ends.\
e) The coding sequences are identified with the CDS acronym in the `FEATURES` section of each `LOCUS`.

::: {.callout-warning collapse="TRUE" appearance="simple"}
## Solution

a\) FALSE. Prokka successfully identifies non-coding sequences and doesn’t translate them. Instead, it provides alternative information (e.g. if it’s a rRNA gene, it tells if it’s 5S, 16S, or 23S).\
b) TRUE. Some coding sequences produce proteins that are marked as “hypothetical”, meaning that they haven’t been yet identified but seem to show properties of a coding sequence.\
c) FALSE. Every tRNA feature has a `/note` subsection mentioning between parentheses the anticodon located on the tRNA.\
d) FALSE. Right next to each feature, there’s a pair of numbers indicating the starting and ending position of the corresponding feature.\
e) TRUE. Each coding sequence is identified by the CDS acronym on the left and information such as coordinates, gene name, locus tag, product description and translation on the right.
:::
::::

## **Annotating multiple genomes**

Now that we know how to annotate genomes with Prokka we can annotate all of the *S. agalactiae* in one run. For this purpose, we will use a complex `while` loop that, for each of the *S. agalactiae* genomes, first extracts the strain name and saves it in a variable, and then uses it inside the Prokka command.

To get the strain names easily we will update our `TettelinList.txt` to add the strain names that it does not have and change the problematic name of the strain 2603V/R. We could just open the file in nano and edit it, but we will do it by coding the changes.\
With `echo` we will add each strain name in a new line, and with `sed` we will remove the characters `/R` of the problematic strain name.

``` bash
$ cd ~/pan_workshop/data/
$ echo "18RS21" >> TettelinList.txt 
$ echo "H36B" >> TettelinList.txt
$ echo "515" >> TettelinList.txt 
$ sed -i 's/\/R//' TettelinList.txt
$ cat TettelinList.txt
```
